trigger:
  - main

variables:
  ACR_NAME: 'youruniquenameacr123'  # set in pipeline variables
  RESOURCE_GROUP: 'msdemo-rg'
  WEBAPP_DATABASE: 'msdemo-database'
  WEBAPP_USER: 'msdemo-user'
  IMAGE_TAG: '$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'services/database-service/pom.xml'
              goals: 'package -DskipTests'
          - task: Maven@3
            inputs:
              mavenPomFile: 'services/user-service/pom.xml'
              goals: 'package -DskipTests'

          - script: |
              az acr login --name $(ACR_NAME)
              docker build -t $(ACR_NAME).azurecr.io/database-service:$(IMAGE_TAG) ./services/database-service
              docker build -t $(ACR_NAME).azurecr.io/user-service:$(IMAGE_TAG) ./services/user-service
              docker push $(ACR_NAME).azurecr.io/database-service:$(IMAGE_TAG)
              docker push $(ACR_NAME).azurecr.io/user-service:$(IMAGE_TAG)
            displayName: Build & Push images

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployWebApps
        environment: 'demo'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    az webapp config container set --name $(WEBAPP_DATABASE) --resource-group $(RESOURCE_GROUP) \
                    --docker-custom-image-name $(ACR_NAME).azurecr.io/database-service:$(IMAGE_TAG) \
                    --docker-registry-server-url https://$(ACR_NAME).azurecr.io
                    
                    az webapp config container set --name $(WEBAPP_USER) --resource-group $(RESOURCE_GROUP) \
                    --docker-custom-image-name $(ACR_NAME).azurecr.io/user-service:$(IMAGE_TAG) \
                    --docker-registry-server-url https://$(ACR_NAME).azurecr.io
                  displayName: Deploy container images to App Service
