name: CI Pipeline

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [microservice-1, microservice-2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: mvn clean verify
